name: Release
on:
  push:
    tags:
      - "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.14'
    - name: Install Compilers
      run: |
        sudo apt-get update
        sudo apt-get install --yes build-essential pkgconf libelf-dev llvm-12 clang-12
        for tool in "clang" "llc" "llvm-strip"
        do
          sudo rm -f /usr/bin/$tool
          sudo ln -s /usr/bin/$tool-12 /usr/bin/$tool
        done
      shell: bash
    - name: authenticate
      run: |
        gh auth login --with-token <<<'${{ secrets.GITHUB_TOKEN }}'
    - name: Release
      run: |
        make -f builder/Makefile.release release SNAPSHOT_VERSION=${{ steps.vars.outputs.tag }}